Add download and time interval refresh
bpptkg/display-device pull request #7
Opened 2022-03-16 07:10 UTC by fajarutamaa

2022-03-21 03:03 UTC, indrarudianto commented on src/views/edm/EDMBenchmarkChart.vue
> +      console.log('Updating EDM Benchmark Chart...')
Remove any `console.log`, it only used for testing and should be removed on the production environment.

2022-03-21 03:06 UTC, indrarudianto commented on src/views/edm/EDMOverviewChart.vue
> +      console.log('Updating EDM Chart....')
Remove `console.log`.

2022-03-21 03:07 UTC, indrarudianto commented on src/views/gps/baseline/GPSBaselineChart.vue
> +    console.log('Updating GPSBaseline Chart...')
Remove `console.log`.

2022-03-21 03:08 UTC, indrarudianto commented on src/views/seismic/SeismicEnergyChart.vue
> +      console.log('Updating Seismic Energy Chart...')
Remove `console.log`.

2022-03-21 03:09 UTC, indrarudianto commented on src/views/weather/babadan/PressureChart.vue
> +      console.log('Updating Pressure Chart...')
Remove `console.log`.

2022-03-21 03:14 UTC, indrarudianto commented on src/views/weather/babadan/RainfallChart.vue
> +      console.log('Updating Rainfall Chart...')
Remove `console.log`.

2022-03-21 03:16 UTC, indrarudianto commented on src/views/weather/pasarbubar/PressureChart.vue
> +      console.log('Updating Pressure Chart...')
Remove `console.log`.

2022-03-21 03:17 UTC, indrarudianto commented on src/views/weather/pasarbubar/RainfallChart.vue
> +      console.log('Updating Rainfall Chart...')
Remove `console.log`.

2022-03-21 03:17 UTC, indrarudianto commented on src/views/weather/pasarbubar/WindRoseChart.vue
> +//import MoreMenu from '@/components/more-menu'
Remove unnecessary comment

2022-03-21 03:17 UTC, indrarudianto commented on src/views/weather/pasarbubar/WindRoseChart.vue
> +  },*/
Remove unused code

2022-03-21 03:19 UTC, indrarudianto requested changes
Remove unused `console.log`.
Remove unnecessary comments.
Remove unused code.

2022-03-21 08:51 UTC, fajarutamaa commented
Okey sir, it's done. Please check again. Thank you 👍

2022-03-22 07:17 UTC, indrarudianto approved these changes

2022-03-22 07:18 UTC, merged